name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, ready_for_review, edited]

jobs:
    markdownlint:
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/vanilla-os/pico:main
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
               node-version: '20'
            - name: Run markdownlint
              run: |
                npm install -g markdownlint-cli
                markdownlint $(find . -name '*.md' | grep -vF './.git') > lint-result.txt
            - name: Comment PR if lint errors
              uses: actions/github-script@v7
              if: ${{ failure() }}
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                  const fs = require('fs');
                  const lintResult = fs.readFileSync('lint-result.txt', 'utf8');
                  if (lintResult) {
                    const issue_number = github.context.issue.number;
                    const owner = github.context.repo.owner;
                    const repo = github.context.repo.repo;
                    github.rest.issues.createComment({
                      issue_number: issue_number,
                      owner: owner,
                      repo: repo,
                      body: `Markdown lint errors:\n${lintResult}`
                    });
                  }
    
    codespell:
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/vanilla-os/pico:main
        steps:
        - uses: actions/checkout@v4
        - uses: codespell-project/actions-codespell@v2
          with:
             path: |
                 articles/en
             only_warn: 1
